from yacs.config import CfgNode as CN

_C = CN()

# Denoising model Parameters
_C.MODEL = CN()
_C.MODEL.OUT_CH = 1
_C.MODEL.WEIGHTS = ""
_C.MODEL.FETCH_PRETRAINED = False
_C.MODEL.STRICT_WEIGHTS = True
_C.MODEL.DROP_PATH = 0.0
_C.MODEL.ADD_REFINER = True

# Encoder Model Parameters
_C.MODEL.ENCODER = CN()

_C.MODEL.DENOISER = CN()
_C.MODEL.DENOISER.CONCAT_DIM = 256

_C.MODEL.TEXT_ENCODER = CN()
_C.MODEL.TEXT_ENCODER.VERSION = "clip-vit-large-p14"
_C.MODEL.TEXT_ENCODER.HIDDEN_DIM = 768
_C.MODEL.TEXT_ENCODER.HIDDEN_DIM_2 = None
_C.MODEL.TEXT_ENCODER.TOKEN_LIMIT = 77
_C.MODEL.TEXT_ENCODER.ZERO_OUT = "none"

_C.MODEL.EMBED_TYPE = "default"

_C.MODEL.CONDITION = "CLASS"

# Solver Parameters.
_C.SOLVER = CN()
_C.SOLVER.IM_SIZE = 256
_C.SOLVER.EPOCHS = 500
_C.SOLVER.MAX_ITER = 999999999
_C.SOLVER.LR = 0.0001
_C.SOLVER.BATCH_SIZE = 64
_C.SOLVER.DEC_BATCH_SIZE = 32
_C.SOLVER.EXTRA_BATCH_SIZE = 16
_C.SOLVER.LOG_EVERY = 20
_C.SOLVER.AMP = True
_C.SOLVER.AMP_TYPE = "fp16"
_C.SOLVER.LOG_WANDB = False
_C.SOLVER.SNAPSHOT_F = 1000
_C.SOLVER.OPTIM = "Adam"
_C.SOLVER.WEIGHT_DECAY = 3e-2
_C.SOLVER.CKPT_EVERY = 2500
_C.SOLVER.KEEP_CKPT_EVERY = 50000
_C.SOLVER.EVAL_FREQ = 10000
_C.SOLVER.EVAL_FID = False
_C.SOLVER.COMPILE_MODELS = False
_C.SOLVER.CLIP_GRAD_NORM = True
_C.SOLVER.MAX_GRAD_NORM = 0.01
_C.SOLVER.TRAINER = "DDPM"
_C.SOLVER.ACCUMULATE = 1

_C.SOLVER.CKPT_ACT = False

_C.SOLVER.PREFETCH = 2

_C.SOLVER.BETA1 = 0.9
_C.SOLVER.BETA2 = 0.999

_C.SOLVER.LR_SCHEDULER = CN()
_C.SOLVER.LR_SCHEDULER.NAME = "constant"
_C.SOLVER.LR_SCHEDULER.START_ITER = 10000000
_C.SOLVER.LR_SCHEDULER.DECAY_LENGTH = 50000
_C.SOLVER.LR_SCHEDULER.WARMUP_LENGTH = 500
_C.SOLVER.LR_SCHEDULER.MIN_LR = 1e-7

_C.SOLVER.FSDP = CN()
_C.SOLVER.FSDP.WRAP_CONDITIONER = True

_C.SOLVER.EMA_DECAY = 0.9999
_C.SOLVER.EMA_START = 500
_C.SOLVER.USE_CFG = False
_C.SOLVER.CFG_DROP_P = 0.1
_C.SOLVER.IMAGE_ONLY = False


_C.FRAMEWORK = CN()
_C.FRAMEWORK.TIMESTEPS = 1000
_C.FRAMEWORK.SIGMA_SCALE = 1.0
_C.FRAMEWORK.DENOISER = "DENOISER"

_C.FRAMEWORK.VIDEO = CN()
_C.FRAMEWORK.VIDEO.REPA = CN()
_C.FRAMEWORK.VIDEO.REPA.LAYER = -1  # 10
_C.FRAMEWORK.VIDEO.REPA.EMB_DIM = 1024

_C.SAMPLER = CN()
_C.SAMPLER.NUM_STEPS = 50
_C.SAMPLER.CFG_SCALE = 4.0

_C.SAMPLER.APG = CN()
_C.SAMPLER.APG.ENABLE = False
_C.SAMPLER.APG.ETA = 0.0
_C.SAMPLER.APG.NORM_THRESHOLD = 5.0
_C.SAMPLER.APG.MOMENTUM = -0.75

_C.SAMPLER.UNCOND_GEN = False

_C.SAMPLER.IMAGE_GUIDANCE_SCALE = -1.0


_C.LOGGING = CN()
_C.LOGGING.LOG_LEVEL = "INFO"


# Data Parameters
_C.DATA = CN()
_C.DATA.WORKERS = 4
_C.DATA.NUM_CLASSES = 1000
_C.DATA.DATASET = "toy_coloring"
_C.DATA.VAL_DATASET = ""

_C.DATA.ANNOT_TRAIN = ""
_C.DATA.ANNOT_VAL = ""

_C.DATA.ENTROPY_THRESHOLD = 3.5

_C.DATA.DATA_ROOT = ""
_C.DATA.VAL_DATA_ROOT = ""
_C.DATA.CROP_SCALE = 0.9
_C.DATA.CLUSTER = "local"
_C.DATA.DATASET_VARIANT = "original"
_C.DATA.VAL_DATASET_VARIANT = ""
_C.DATA.DATALOADER_STYLE = "map_style"

_C.DATA.CAPTION_IDX = ["1", "2"]

_C.DATA.AESTHETIC_COND = False
_C.DATA.FLIP_COND = False
_C.DATA.BLUR_COND = False

_C.DATA.RECAPTION = CN()
_C.DATA.RECAPTION.RECAPTIONED_RATIO = 0.75

_C.DATA.POWER_COSINE = False

_C.DATA.VIDEO = CN()
_C.DATA.VIDEO.MIN_MOTION_SCORE = -1.0
_C.DATA.VIDEO.SAMPLING_FPS = 24
_C.DATA.EXTRA_DATASETS = None

# Video Model args
_C.DATA.MAX_FRAMES = 73
_C.DATA.NUM_CONTEXT_FRAMES = 1

_C.DATA.MIN_SUBJECTNESS = 0.4
_C.DATA.MIN_SIZE_RATIO = 0.05
_C.DATA.MAX_SIZE_RATIO = 0.9

_C.DATA.PADDING_INDEX = 50

# Eval params
_C.EVAL = CN()
_C.EVAL.GROUPS = []

_C.EVAL.FID = CN()
_C.EVAL.FID.SAMPLER = "euler"
_C.EVAL.FID.SKIP_F = 4
_C.EVAL.FID.TARGET_DATASET = "val"

_C.EVAL.GROUPS_COUNT = 5
_C.EVAL.NUM_SAMPLES = 256

# Autoencoder parameters
_C.MODEL.VAE = CN()
_C.MODEL.VAE.NAME = "IDENTITY"
_C.MODEL.VAE.CHECKPOINT = ""
_C.MODEL.VAE.FACTOR = 1
_C.MODEL.VAE.OUT_CH = 3
_C.MODEL.VAE.SCALE_FACTOR = 1.0
_C.MODEL.VAE.SHIFT_FACTOR = 0.0
_C.MODEL.VAE.TEMPORAL_FACTOR = 1

_C.MODEL.VAE.NORMALIZE_LATENTS = False

_C.MODEL.TEMPORAL_DOWNSCALING = 3

_C.MODEL.VIDEO = CN()
_C.MODEL.VIDEO.ATTENTION_MASK = "causal_t2i"
_C.MODEL.VIDEO.RD_MASK_FIRST_FRAME = True
_C.MODEL.VIDEO.ROPE_THETA = 10_000
_C.MODEL.VIDEO.ROPE_MODE = "global"

_C.MODEL.VIDEO.ROPE_H_MULT = 200
_C.MODEL.VIDEO.ROPE_W_MULT = 200
_C.MODEL.VIDEO.ROPE_T_MULT = 20
_C.MODEL.VIDEO.CONTEXT_LATENTS = 1
_C.MODEL.VIDEO.CONTEXT_FRAMES = 1

_C.MODEL.VIDEO.POOL_Y_EMB = True
_C.MODEL.VIDEO.IMG_ENC_RES = 252

# misc params
_C.JOB_ID = 0
_C.RUN_ID = None

_C.FLOWCEPTION = CN()
_C.FLOWCEPTION.KAPPA_SCHEDULER = "linear"
_C.FLOWCEPTION.NUM_START_FRAMES = 2
_C.FLOWCEPTION.ATTN_WINDOW = 1
_C.FLOWCEPTION.TAU_GLOBAL_DIST = "uniform"

_C.FLOWCEPTION.ARCHITECTURE = CN()
_C.FLOWCEPTION.ARCHITECTURE.HEAD_SHARED_OFFSETS = False
_C.FLOWCEPTION.ARCHITECTURE.MERGE_MODE = "deformable"

_C.FLOWCEPTION.LOSS = CN()
_C.FLOWCEPTION.LOSS.IMG_WEIGHT = 1.0
_C.FLOWCEPTION.LOSS.POISSON_WEIGHT = 1.0

_C.FLOWCEPTION.SAMPLING = CN()
_C.FLOWCEPTION.SAMPLING.INSERTION_RULE = "learned"
_C.FLOWCEPTION.SAMPLING.GUIDANCE_OFFSET = 0.1
_C.FLOWCEPTION.SAMPLING.GUIDANCE_INS = 1.0


def get_cfg_defaults():
    return _C.clone()
